<?xml version="1.0" encoding="utf-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:in="https://incomaker.com/feed/v4"
    elementFormDefault="qualified"
>
    <xs:import namespace="https://incomaker.com/feed/v4" schemaLocation="incomaker.xsd"/>
    <xs:element name="categories">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="in:feed">
                    <xs:sequence>
                        <xs:element minOccurs="0" maxOccurs="unbounded" name="c">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element minOccurs="0" name="parentCategoryId" type="xs:string"/>
                                    <xs:element name="languages">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element maxOccurs="unbounded" name="l">
                                                    <xs:complexType>
                                                        <xs:all>
                                                            <xs:element name="name" type="xs:string"/>
                                                            <xs:element name="url" type="xs:string" minOccurs="0"/>
                                                        </xs:all>
                                                        <xs:attribute name="id" use="required"/>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element minOccurs="0" name="customFields">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element maxOccurs="unbounded" name="f">
                                                    <xs:complexType>
                                                        <xs:simpleContent>
                                                            <xs:extension base="xs:string">
                                                                <xs:attribute name="key" type="xs:string" use="required"/>
                                                                <xs:attribute name="group" type="xs:string"/>
                                                            </xs:extension>
                                                        </xs:simpleContent>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:all>
                                <xs:attribute type="xs:string" name="id" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
</xs:schema>
